"""empty message

Revision ID: d75fe2c1a0bd
Revises: 69442ca1d943
Create Date: 2021-01-20 17:23:10.166358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75fe2c1a0bd'
down_revision = '69442ca1d943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ad_frequency', sa.Interval(), nullable=True),
    sa.Column('ad_start_time', sa.Time(), nullable=True),
    sa.Column('ad_end_time', sa.Time(), nullable=True),
    sa.Column('ad_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_settings')
    # ### end Alembic commands ###
